apiVersion: v1
kind: Service
metadata:
  name: name-the-footballer-backend
  labels:
    app: name-the-footballer-backend
spec:
  type: NodePort
  selector:
    app: name-the-footballer-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001