apiVersion: v1
kind: Service
metadata:
  name: name-the-footballer-frontend
  labels:
    app: name-the-footballer-frontend
spec:
  type: NodePort
  selector:
    app: name-the-footballer-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000