backend:
  image:
    repository: name-the-footballer-backend
    tag: latest
    pullPolicy: Never
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

frontend:
  image:
    repository: name-the-footballer-frontend
    tag: latest
    pullPolicy: Never
  replicaCount: 1
  env:
    - name: REACT_APP_BACKEND_URL
      value: "http://name-the-footballer-backend:3001"